### ISSUE TITLE
Visualizing 3d objects

### ISSUE THREAD

**Issue by kirillantonov2901** [hoffstadt/DearPy3D#5]
Hello, thanks for DPG, it really saved me)
I asked about 3d drawings in dpq project. How can i try Marvel? Install via pycharm etc...?
My goal is to visualize cubes importing vex coords (x,y,z). Maybe you can show me direction how to start solving this question?)

**Comment by hoffstadt** [comment]
Hi, glad to hear!

I apologize but we haven't written a python wrapping for it yet and it's only on windows at the moment!
